use sha2::{Digest, Sha256};
use std::{collections::BTreeMap, fs, path::Path};

pub(super) fn payload(root: &Path) -> BTreeMap<String, Vec<u8>> {
    let names = fs::read_to_string(root.join("files.list")).unwrap();
    names
        .lines()
        .chain(["files.list", "files.sha256"])
        .map(|path| (path.to_owned(), fs::read(root.join(path)).unwrap()))
        .collect()
}

// A mutable owner ledger and recomputed seal must never authorize altered
// generated bytes or a fabricated product identity.
pub(super) fn reseal(root: &Path) {
    let path = root.join("workbench-ownership.json");
    let mut ledger: serde_json::Value = serde_json::from_slice(&fs::read(&path).unwrap()).unwrap();
    for entry in ledger["files"].as_array_mut().unwrap() {
        let bytes = fs::read(root.join(entry["path"].as_str().unwrap())).unwrap();
        entry["sha256"] = serde_json::Value::String(format!("{:x}", Sha256::digest(bytes)));
    }
    let mut bytes = serde_json::to_vec_pretty(&ledger).unwrap();
    bytes.push(b'\n');
    fs::write(path, bytes).unwrap();
    seal(root);
}

pub(super) fn seal(root: &Path) {
    let names = fs::read_to_string(root.join("files.list")).unwrap();
    let mut seal = String::new();
    for path in names.lines().chain(["files.list"]) {
        seal.push_str(&format!(
            "{:x}  {path}\n",
            Sha256::digest(fs::read(root.join(path)).unwrap())
        ));
    }
    fs::write(root.join("files.sha256"), seal).unwrap();
}
