use super::tooling;
use super::workspace::Scratch;
use autosar_config_core::definitions::DefinitionCatalog;
use autosar_config_core::generator::delivery;
use autosar_config_core::{Workspace, prepare_host_project};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

fn signals(root: &Path) -> Workspace {
    let preview = Workspace::preview_project_creation(root, "Delivery", "can-signals-v1").unwrap();
    Workspace::create_project_previewed(&preview).unwrap()
}

fn payload(root: &Path) -> BTreeMap<String, Vec<u8>> {
    let names = fs::read_to_string(root.join("files.list")).unwrap();
    names
        .lines()
        .chain(["files.list", "files.sha256"])
        .map(|path| (path.to_owned(), fs::read(root.join(path)).unwrap()))
        .collect()
}

// A mutable owner ledger and recomputed seal must never authorize altered
// generated bytes or a fabricated product identity.
fn reseal(root: &Path) {
    let path = root.join("workbench-ownership.json");
    let mut ledger: serde_json::Value = serde_json::from_slice(&fs::read(&path).unwrap()).unwrap();
    for entry in ledger["files"].as_array_mut().unwrap() {
        let bytes = fs::read(root.join(entry["path"].as_str().unwrap())).unwrap();
        entry["sha256"] = serde_json::Value::String(format!("{:x}", Sha256::digest(bytes)));
    }
    let mut bytes = serde_json::to_vec_pretty(&ledger).unwrap();
    bytes.push(b'\n');
    fs::write(path, bytes).unwrap();
    let names = fs::read_to_string(root.join("files.list")).unwrap();
    let mut seal = String::new();
    for path in names.lines().chain(["files.list"]) {
        seal.push_str(&format!(
            "{:x}  {path}\n",
            Sha256::digest(fs::read(root.join(path)).unwrap())
        ));
    }
    fs::write(root.join("files.sha256"), seal).unwrap();
}

#[test]
fn builtin_can_handoff_reconstructs_independent_authoritative_members() {
    let scratch = Scratch::new();
    let live = scratch.0.join("Live");
    let mut workspace = signals(&live);
    let before = workspace.generation_snapshot().unwrap();
    let output = scratch.0.join("package");
    prepare_host_project(&mut workspace, tooling::native_target(), true)
        .unwrap()
        .generate(&output)
        .unwrap();
    let mut imported = delivery::open_handoff(
        &output,
        &scratch.0.join("Receiver"),
        &DefinitionCatalog::builtin().unwrap(),
    )
    .unwrap();
    assert!(!imported.workspace.uses_legacy_validation());
    let actual = imported.workspace.generation_snapshot().unwrap();
    let expected: BTreeMap<_, _> = before
        .inputs
        .iter()
        .map(|input| (&input.logical_path, &input.bytes))
        .collect();
    let received: BTreeMap<_, _> = actual
        .inputs
        .iter()
        .map(|input| (&input.logical_path, &input.bytes))
        .collect();
    assert_eq!(received, expected);
    let live = fs::canonicalize(&live).unwrap();
    for input in actual.inputs {
        assert!(
            !fs::canonicalize(input.disk_path)
                .unwrap()
                .starts_with(&live)
        );
    }
    let reproduced = scratch.0.join("reproduced");
    prepare_host_project(&mut imported.workspace, tooling::native_target(), true)
        .unwrap()
        .generate(&reproduced)
        .unwrap();
    assert_eq!(payload(&output), payload(&reproduced));
}

#[test]
fn builtin_can_resealed_generated_bytes_cannot_self_authorize_import_or_replacement() {
    let scratch = Scratch::new();
    let mut workspace = signals(&scratch.0.join("Live"));
    let output = scratch.0.join("package");
    prepare_host_project(&mut workspace, tooling::native_target(), true)
        .unwrap()
        .generate(&output)
        .unwrap();
    let original = fs::read(output.join("Ecu_Config.c")).unwrap();
    let mut changed = original.clone();
    changed.extend_from_slice(b"\n#error Unauthorized_generated_change\n");
    fs::write(output.join("Ecu_Config.c"), &changed).unwrap();
    reseal(&output);
    let receiver = scratch.0.join("Receiver");
    assert!(
        delivery::open_handoff(&output, &receiver, &DefinitionCatalog::builtin().unwrap()).is_err()
    );
    assert!(!receiver.exists());
    assert!(
        prepare_host_project(&mut workspace, tooling::native_target(), true)
            .unwrap()
            .preview(&output)
            .is_err()
    );
    assert_eq!(fs::read(output.join("Ecu_Config.c")).unwrap(), changed);
}

#[test]
fn builtin_can_resealed_rule_identity_is_not_a_trusted_native_resource() {
    let scratch = Scratch::new();
    let mut workspace = signals(&scratch.0.join("Live"));
    let output = scratch.0.join("package");
    prepare_host_project(&mut workspace, tooling::native_target(), true)
        .unwrap()
        .generate(&output)
        .unwrap();
    for path in ["handoff.json", "target.json"] {
        let mut value: serde_json::Value =
            serde_json::from_slice(&fs::read(output.join(path)).unwrap()).unwrap();
        let metadata = if path == "target.json" {
            &mut value["nativeDelivery"]
        } else {
            &mut value
        };
        metadata["resourceIdentities"]["ruleSetIdentity"]["rulesVersion"] =
            "untrusted-version".into();
        fs::write(
            output.join(path),
            serde_json::to_vec_pretty(&value).unwrap(),
        )
        .unwrap();
    }
    reseal(&output);
    let receiver = scratch.0.join("Receiver");
    assert!(
        delivery::open_handoff(&output, &receiver, &DefinitionCatalog::builtin().unwrap()).is_err()
    );
    assert!(!receiver.exists());
    workspace.generation_snapshot().unwrap();
}

#[test]
fn builtin_can_generation_never_installs_inside_authoritative_source_tree() {
    let scratch = Scratch::new();
    let live = scratch.0.join("Live");
    let mut workspace = signals(&live);
    let before = workspace.generation_snapshot().unwrap();
    let output = live.join("generated");
    assert!(
        prepare_host_project(&mut workspace, tooling::native_target(), false)
            .unwrap()
            .preview(&output)
            .is_err()
    );
    assert!(
        prepare_host_project(&mut workspace, tooling::native_target(), false)
            .unwrap()
            .generate(&output)
            .is_err()
    );
    assert!(!output.exists());
    for input in before.inputs {
        assert_eq!(fs::read(input.disk_path).unwrap(), input.bytes);
    }
}

#[test]
fn builtin_can_late_source_edit_refuses_staged_commit_and_preserves_output() {
    let scratch = Scratch::new();
    let mut workspace = signals(&scratch.0.join("Live"));
    let output = scratch.0.join("package");
    prepare_host_project(&mut workspace, tooling::native_target(), true)
        .unwrap()
        .generate(&output)
        .unwrap();
    let original = payload(&output);
    let prepared = prepare_host_project(&mut workspace, tooling::native_target(), true).unwrap();
    let preview = prepare_host_project(&mut workspace, tooling::native_target(), true)
        .unwrap()
        .preview(&output)
        .unwrap();
    let staged = prepared
        .stage_previewed(&output, &preview.revision)
        .unwrap();
    let snapshot = workspace.generation_snapshot().unwrap();
    let input = &snapshot.inputs[0];
    let mut changed = input.bytes.clone();
    changed.extend_from_slice(b"\n<!-- external source edit -->\n");
    fs::write(&input.disk_path, &changed).unwrap();
    assert!(staged.commit().is_err());
    assert_eq!(payload(&output), original);
    assert_eq!(fs::read(&input.disk_path).unwrap(), changed);
}

fn standard_with_application(root: &Path) -> Workspace {
    let creation =
        Workspace::preview_project_creation(root, "Application", "standard-ecu-v1").unwrap();
    let mut workspace = Workspace::create_project_previewed(&creation).unwrap();
    let initialization = workspace.preview_application_initialization().unwrap();
    workspace
        .initialize_application_previewed(&initialization)
        .unwrap();
    workspace
}

#[test]
fn builtin_ecu_handoff_preserves_user_algorithm_in_independent_reconstructed_project() {
    use autosar_config_core::integration::RuntimeCatalog;
    use autosar_config_core::prepared::prepare_ecu_project_for_workspace;
    let scratch = Scratch::new();
    let live = scratch.0.join("Live");
    let workspace = standard_with_application(&live);
    let application = &workspace.generation_snapshot().unwrap().applications[0];
    let original = String::from_utf8(application.bytes.clone()).unwrap();
    let changed = original
        .replace(
            "Data[i] = (uint8)(application.value >> ((3u - i) * 8u));",
            "Data[i] = (uint8)((application.value + UINT32_C(1)) >> ((3u - i) * 8u));",
        )
        .into_bytes();
    assert_ne!(changed, application.bytes);
    fs::write(&application.disk_path, &changed).unwrap();
    let workspace = Workspace::open_project_manifest(
        &live.join("workbench-project.json"),
        &scratch.0.join("cache"),
    )
    .unwrap();
    let runtime = RuntimeCatalog::embedded().unwrap();
    let plan = workspace.saved_integration_plan(&runtime).unwrap();
    let output = scratch.0.join("package");
    prepare_ecu_project_for_workspace(&workspace, &plan, tooling::native_target(), true)
        .unwrap()
        .generate(&output)
        .unwrap();
    assert_eq!(fs::read(output.join("src/Application.c")).unwrap(), changed);
    assert_eq!(fs::read(&application.disk_path).unwrap(), changed);
    let receiver = scratch.0.join("Receiver");
    let imported =
        delivery::open_handoff(&output, &receiver, &DefinitionCatalog::builtin().unwrap()).unwrap();
    let actual = imported.workspace.generation_snapshot().unwrap();
    assert_eq!(actual.applications[0].bytes, changed);
    assert!(
        fs::canonicalize(&actual.applications[0].disk_path)
            .unwrap()
            .starts_with(fs::canonicalize(&receiver).unwrap())
    );
    let receiver_plan = imported.workspace.saved_integration_plan(&runtime).unwrap();
    let reproduced = scratch.0.join("reproduced");
    prepare_ecu_project_for_workspace(
        &imported.workspace,
        &receiver_plan,
        tooling::native_target(),
        true,
    )
    .unwrap()
    .generate(&reproduced)
    .unwrap();
    assert_eq!(payload(&output), payload(&reproduced));
}

#[test]
fn builtin_ecu_late_live_edit_and_resealed_snapshot_never_overwrite_user_bytes_or_prior_output() {
    use autosar_config_core::integration::RuntimeCatalog;
    use autosar_config_core::prepared::prepare_ecu_project_for_workspace;
    let scratch = Scratch::new();
    let workspace = standard_with_application(&scratch.0.join("Live"));
    let runtime = RuntimeCatalog::embedded().unwrap();
    let plan = workspace.saved_integration_plan(&runtime).unwrap();
    let output = scratch.0.join("package");
    prepare_ecu_project_for_workspace(&workspace, &plan, tooling::native_target(), true)
        .unwrap()
        .generate(&output)
        .unwrap();
    let original = payload(&output);
    let prepared =
        prepare_ecu_project_for_workspace(&workspace, &plan, tooling::native_target(), true)
            .unwrap();
    let preview =
        prepare_ecu_project_for_workspace(&workspace, &plan, tooling::native_target(), true)
            .unwrap()
            .preview(&output)
            .unwrap();
    let staged = prepared
        .stage_previewed(&output, &preview.revision)
        .unwrap();
    let snapshot = workspace.generation_snapshot().unwrap();
    let application = &snapshot.applications[0];
    let mut changed = application.bytes.clone();
    changed.extend_from_slice(b"\n/* external live user edit */\n");
    fs::write(&application.disk_path, &changed).unwrap();
    assert!(staged.commit().is_err());
    assert_eq!(payload(&output), original);
    assert_eq!(fs::read(&application.disk_path).unwrap(), changed);
    fs::write(
        output.join("src/Application.c"),
        b"#error Altered_sealed_application_snapshot\n",
    )
    .unwrap();
    reseal(&output);
    let receiver = scratch.0.join("Receiver");
    assert!(
        delivery::open_handoff(&output, &receiver, &DefinitionCatalog::builtin().unwrap()).is_err()
    );
    assert!(!receiver.exists());
    assert_eq!(fs::read(&application.disk_path).unwrap(), changed);
}

#[test]
fn builtin_handoff_rejects_unknown_owner_and_ownership_version_without_publishing() {
    let scratch = Scratch::new();
    let mut workspace = signals(&scratch.0.join("Live"));
    for version in [false, true] {
        let output = scratch.0.join(if version { "version" } else { "owner" });
        prepare_host_project(&mut workspace, tooling::native_target(), true)
            .unwrap()
            .generate(&output)
            .unwrap();
        let ledger_path = output.join("workbench-ownership.json");
        let mut ledger: serde_json::Value =
            serde_json::from_slice(&fs::read(&ledger_path).unwrap()).unwrap();
        if version {
            ledger["formatVersion"] = 2.into();
        } else {
            ledger["files"][0]["owner"] = "unrecognized-authority".into();
        }
        fs::write(ledger_path, serde_json::to_vec_pretty(&ledger).unwrap()).unwrap();
        reseal(&output);
        let corrupted = payload(&output);
        let receiver = scratch.0.join(if version {
            "version-receiver"
        } else {
            "owner-receiver"
        });
        assert!(
            delivery::open_handoff(&output, &receiver, &DefinitionCatalog::builtin().unwrap())
                .is_err()
        );
        assert!(!receiver.exists());
        assert_eq!(payload(&output), corrupted);
    }
}

#[test]
fn builtin_handoff_rejects_forged_declared_extension_identity_without_publishing() {
    let scratch = Scratch::new();
    let mut workspace = signals(&scratch.0.join("Live"));
    let output = scratch.0.join("package");
    prepare_host_project(&mut workspace, tooling::native_target(), true)
        .unwrap()
        .generate(&output)
        .unwrap();
    let identity = serde_json::json!({
        "catalogId": "not-explicitly-accepted", "release": "R24-11",
        "version": "1.0.0", "sha256": "a".repeat(64),
    });
    for path in ["handoff.json", "target.json"] {
        let mut value: serde_json::Value =
            serde_json::from_slice(&fs::read(output.join(path)).unwrap()).unwrap();
        let metadata = if path == "target.json" {
            &mut value["nativeDelivery"]
        } else {
            &mut value
        };
        metadata["resourceIdentities"]["requiredExtensionDefinitions"] =
            serde_json::json!([identity]);
        fs::write(
            output.join(path),
            serde_json::to_vec_pretty(&value).unwrap(),
        )
        .unwrap();
    }
    reseal(&output);
    let receiver = scratch.0.join("Receiver");
    let before = workspace.generation_snapshot().unwrap();
    assert!(
        delivery::open_handoff(&output, &receiver, &DefinitionCatalog::builtin().unwrap()).is_err()
    );
    assert!(!receiver.exists());
    for input in before.inputs {
        assert_eq!(fs::read(input.disk_path).unwrap(), input.bytes);
    }
}

fn edit_standard_configuration(root: &Path, edit: impl FnOnce(&str) -> String) -> Workspace {
    let creation =
        Workspace::preview_project_creation(root, "Qualified", "standard-ecu-v1").unwrap();
    let workspace = Workspace::create_project_previewed(&creation).unwrap();
    let runtime = autosar_config_core::integration::RuntimeCatalog::embedded().unwrap();
    workspace.saved_integration_plan(&runtime).unwrap();
    let path = root.join("ecuc.arxml");
    let original = fs::read_to_string(&path).unwrap();
    let changed = edit(&original);
    assert_ne!(changed, original);
    fs::write(&path, &changed).unwrap();
    drop(workspace);
    Workspace::open_project_manifest(&root.join("workbench-project.json"), &root.join("cache"))
        .unwrap()
}

fn assert_native_generation_rejected(workspace: &Workspace, output: &Path) {
    let before = workspace.generation_snapshot().unwrap();
    let prior_output = output.exists().then(|| payload(output));
    let runtime = autosar_config_core::integration::RuntimeCatalog::embedded().unwrap();
    let rejected = match workspace.saved_integration_plan(&runtime) {
        Err(_) => true,
        Ok(plan) => match autosar_config_core::prepared::prepare_ecu_project_for_workspace(
            workspace,
            &plan,
            tooling::native_target(),
            true,
        ) {
            Err(_) => true,
            Ok(prepared) => prepared.generate(output).is_err(),
        },
    };
    assert!(
        rejected,
        "Unqualified target consumers must not produce native sources"
    );
    if let Some(prior) = prior_output {
        assert_eq!(payload(output), prior);
    } else {
        assert!(!output.exists());
    }
    for input in before.inputs {
        assert_eq!(fs::read(input.disk_path).unwrap(), input.bytes);
    }
}

fn ecuc_module<'a, 'input>(
    document: &'a roxmltree::Document<'input>,
    name: &str,
) -> roxmltree::Node<'a, 'input> {
    document
        .descendants()
        .find(|node| {
            node.is_element()
                && node.tag_name().name() == "ECUC-MODULE-CONFIGURATION-VALUES"
                && node.children().any(|child| {
                    child.tag_name().name() == "SHORT-NAME" && child.text() == Some(name)
                })
        })
        .unwrap()
}

#[test]
fn builtin_ecu_generation_rejects_unknown_container_inside_consumed_com_module() {
    let scratch = Scratch::new();
    let workspace = edit_standard_configuration(&scratch.0.join("Live"), |original| {
        let document = roxmltree::Document::parse(original).unwrap();
        let module = ecuc_module(&document, "Com");
        let containers = module
            .children()
            .find(|node| node.is_element() && node.tag_name().name() == "CONTAINERS")
            .unwrap();
        let end = containers.range().end - "</CONTAINERS>".len();
        let mut changed = original.to_owned();
        changed.insert_str(end, "<ECUC-CONTAINER-VALUE><SHORT-NAME>UnqualifiedConsumer</SHORT-NAME><DEFINITION-REF DEST=\"ECUC-PARAM-CONF-CONTAINER-DEF\">/AUTOSAR/EcucDefs/Com/UnmodeledConsumer</DEFINITION-REF></ECUC-CONTAINER-VALUE>");
        changed
    });
    assert_native_generation_rejected(&workspace, &scratch.0.join("output"));
}

#[test]
fn builtin_ecu_generation_qualifies_referenced_clock_semantics_and_module_edition() {
    let scratch = Scratch::new();
    for unsupported_edition in [false, true] {
        let root = scratch.0.join(if unsupported_edition {
            "edition"
        } else {
            "clock"
        });
        let workspace = edit_standard_configuration(&root, |original| {
            let document = roxmltree::Document::parse(original).unwrap();
            let module = ecuc_module(&document, "Mcu");
            let mut changed = original.to_owned();
            if unsupported_edition {
                let edition = module
                    .children()
                    .find(|node| node.is_element() && node.tag_name().name() == "ECUC-DEF-EDITION")
                    .unwrap();
                changed.replace_range(
                    edition.range(),
                    "<ECUC-DEF-EDITION>4.9.0</ECUC-DEF-EDITION>",
                );
            } else {
                let cpu_clock = document
                    .descendants()
                    .find(|node| {
                        node.is_element()
                            && node.tag_name().name() == "ECUC-REFERENCE-VALUE"
                            && node.children().any(|child| {
                                child.tag_name().name() == "DEFINITION-REF"
                                    && child
                                        .text()
                                        .is_some_and(|value| value.ends_with("/CanCpuClockRef"))
                            })
                    })
                    .unwrap();
                let path = cpu_clock
                    .children()
                    .find(|node| node.is_element() && node.tag_name().name() == "VALUE-REF")
                    .unwrap()
                    .text()
                    .unwrap();
                let reference = module
                    .descendants()
                    .find(|node| {
                        node.is_element()
                            && node.tag_name().name() == "ECUC-CONTAINER-VALUE"
                            && node.children().any(|child| {
                                child.tag_name().name() == "SHORT-NAME"
                                    && child.text() == path.rsplit('/').next()
                            })
                    })
                    .unwrap();
                let parameters = reference
                    .children()
                    .find(|node| node.is_element() && node.tag_name().name() == "PARAMETER-VALUES")
                    .unwrap();
                let end = parameters.range().end - "</PARAMETER-VALUES>".len();
                changed.insert_str(end, "<ECUC-NUMERICAL-PARAM-VALUE><DEFINITION-REF DEST=\"ECUC-INTEGER-PARAM-DEF\">/AUTOSAR/EcucDefs/Mcu/McuModuleConfiguration/McuClockSettingConfig/McuClockReferencePoint/UnknownClockPolicy</DEFINITION-REF><VALUE>0</VALUE></ECUC-NUMERICAL-PARAM-VALUE>");
            }
            changed
        });
        assert_native_generation_rejected(
            &workspace,
            &scratch.0.join(if unsupported_edition {
                "edition-output"
            } else {
                "clock-output"
            }),
        );
    }
}

#[test]
fn builtin_ecu_generation_preserves_unrelated_retained_module_without_blocking_target() {
    let scratch = Scratch::new();
    let workspace = edit_standard_configuration(&scratch.0.join("Live"), |original| {
        let document = roxmltree::Document::parse(original).unwrap();
        let module = ecuc_module(&document, "Mcu");
        let name = module
            .children()
            .find(|node| node.is_element() && node.tag_name().name() == "SHORT-NAME")
            .unwrap();
        let edition = module
            .children()
            .find(|node| node.is_element() && node.tag_name().name() == "ECUC-DEF-EDITION")
            .unwrap();
        let range = module.range();
        let mut retained = original[range.clone()].to_owned();
        for (span, value) in [
            (
                edition.range(),
                "<ECUC-DEF-EDITION>4.9.0</ECUC-DEF-EDITION>",
            ),
            (name.range(), "<SHORT-NAME>RetainedMcu</SHORT-NAME>"),
        ] {
            retained.replace_range(span.start - range.start..span.end - range.start, value);
        }
        let mut changed = original.to_owned();
        changed.insert_str(range.end, &retained);
        changed
    });
    let before = workspace.generation_snapshot().unwrap();
    let runtime = autosar_config_core::integration::RuntimeCatalog::embedded().unwrap();
    let plan = workspace.saved_integration_plan(&runtime).unwrap();
    let output = scratch.0.join("output");
    autosar_config_core::prepared::prepare_ecu_project_for_workspace(
        &workspace,
        &plan,
        tooling::native_target(),
        true,
    )
    .unwrap()
    .generate(&output)
    .unwrap();
    let imported = delivery::open_handoff(
        &output,
        &scratch.0.join("Receiver"),
        &DefinitionCatalog::builtin().unwrap(),
    )
    .unwrap();
    let actual = imported.workspace.generation_snapshot().unwrap();
    let expected: BTreeMap<_, _> = before
        .inputs
        .iter()
        .map(|input| (&input.logical_path, &input.bytes))
        .collect();
    let received: BTreeMap<_, _> = actual
        .inputs
        .iter()
        .map(|input| (&input.logical_path, &input.bytes))
        .collect();
    assert_eq!(received, expected);
    for input in before.inputs {
        assert_eq!(fs::read(input.disk_path).unwrap(), input.bytes);
    }
}

fn reject_core_change_with_prior_output(edit: impl FnOnce(&str) -> String) {
    let scratch = Scratch::new();
    let root = scratch.0.join("Live");
    let creation =
        Workspace::preview_project_creation(&root, "CorePolicy", "standard-ecu-v1").unwrap();
    let workspace = Workspace::create_project_previewed(&creation).unwrap();
    let runtime = autosar_config_core::integration::RuntimeCatalog::embedded().unwrap();
    let plan = workspace.saved_integration_plan(&runtime).unwrap();
    let output = scratch.0.join("output");
    autosar_config_core::prepared::prepare_ecu_project_for_workspace(
        &workspace,
        &plan,
        tooling::native_target(),
        true,
    )
    .unwrap()
    .generate(&output)
    .unwrap();
    let path = root.join("ecuc.arxml");
    let original = fs::read_to_string(&path).unwrap();
    let changed = edit(&original);
    assert_ne!(changed, original);
    fs::write(&path, &changed).unwrap();
    drop(workspace);
    let workspace = Workspace::open_project_manifest(
        &root.join("workbench-project.json"),
        &scratch.0.join("cache"),
    )
    .unwrap();
    assert_native_generation_rejected(&workspace, &output);
    assert_eq!(fs::read_to_string(path).unwrap(), changed);
}

fn core_id_parameter<'a, 'input>(
    document: &'a roxmltree::Document<'input>,
) -> roxmltree::Node<'a, 'input> {
    document
        .descendants()
        .find(|node| {
            node.is_element()
                && node.tag_name().name() == "ECUC-NUMERICAL-PARAM-VALUE"
                && node.children().any(|child| {
                    child.tag_name().name() == "DEFINITION-REF"
                        && child
                            .text()
                            .is_some_and(|value| value.ends_with("/EcucCoreId"))
                })
        })
        .unwrap()
}

#[test]
fn builtin_ecu_generation_rejects_definition_valid_nonzero_core_without_replacing_output() {
    reject_core_change_with_prior_output(|original| {
        let document = roxmltree::Document::parse(original).unwrap();
        let parameter = core_id_parameter(&document);
        let definition = parameter
            .children()
            .find(|node| node.is_element() && node.tag_name().name() == "DEFINITION-REF")
            .unwrap()
            .text()
            .unwrap();
        let catalog = DefinitionCatalog::builtin().unwrap();
        let kind = catalog.get(definition).unwrap().kind.unwrap();
        catalog
            .validate_value(
                definition,
                &autosar_config_core::project_model::TypedValue {
                    kind,
                    lexeme: "1".into(),
                },
            )
            .unwrap();
        let value = parameter
            .children()
            .find(|node| node.is_element() && node.tag_name().name() == "VALUE")
            .unwrap();
        let mut changed = original.to_owned();
        changed.replace_range(value.range(), "<VALUE>1</VALUE>");
        changed
    });
}

#[test]
fn builtin_ecu_generation_rejects_second_core_zero_without_replacing_output() {
    reject_core_change_with_prior_output(|original| {
        let document = roxmltree::Document::parse(original).unwrap();
        let parameter = core_id_parameter(&document);
        let core = parameter
            .ancestors()
            .find(|node| node.is_element() && node.tag_name().name() == "ECUC-CONTAINER-VALUE")
            .unwrap();
        let name = core
            .children()
            .find(|node| node.is_element() && node.tag_name().name() == "SHORT-NAME")
            .unwrap();
        let range = core.range();
        let mut second = original[range.clone()].to_owned();
        second.replace_range(
            name.range().start - range.start..name.range().end - range.start,
            "<SHORT-NAME>SecondCoreZero</SHORT-NAME>",
        );
        let mut changed = original.to_owned();
        changed.insert_str(range.end, &second);
        changed
    });
}
