[project]
name = "autosar-tooling"
version = "0.1.0"
requires-python = ">=3.12,<3.13"

[build-system]
requires = ["setuptools==84.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "scripts"}

[tool.setuptools.packages.find]
where = ["scripts"]
include = ["autosar_tooling*", "ecu_tools*"]

[dependency-groups]
quality = ["clang-format==23.1.1", "ruff==0.16.9", "lxml==5.4.0"]
automotive = ["openpyxl==3.1.5", "et-xmlfile==2.0.0"]
