pub(super) fn sources() -> Vec<(String, Vec<u8>)> {
    let sources: &[(&str, &[u8])] = &[
        (
            "src/Can_HostLock.h",
            include_bytes!("../../../runtime/src/Can_HostLock.h"),
        ),
        (
            "src/NvM_HostStorage.h",
            include_bytes!("../../../runtime/src/NvM_HostStorage.h"),
        ),
        (
            "include/Can.h",
            include_bytes!("../../../runtime/include/Can.h"),
        ),
        (
            "include/Can_GeneralTypes.h",
            include_bytes!("../../../runtime/include/Can_GeneralTypes.h"),
        ),
        (
            "include/Can_MemMap.h",
            include_bytes!("../../../runtime/include/Can_MemMap.h"),
        ),
        (
            "include/CanIf.h",
            include_bytes!("../../../runtime/include/CanIf.h"),
        ),
        (
            "include/CanIf_MemMap.h",
            include_bytes!("../../../runtime/include/CanIf_MemMap.h"),
        ),
        (
            "include/CanTp.h",
            include_bytes!("../../../runtime/include/CanTp.h"),
        ),
        (
            "include/Com.h",
            include_bytes!("../../../runtime/include/Com.h"),
        ),
        (
            "include/ComStack_Types.h",
            include_bytes!("../../../runtime/include/ComStack_Types.h"),
        ),
        (
            "include/Dcm.h",
            include_bytes!("../../../runtime/include/Dcm.h"),
        ),
        (
            "include/Dem.h",
            include_bytes!("../../../runtime/include/Dem.h"),
        ),
        (
            "include/Ecu_Config.h",
            include_bytes!("../../../runtime/include/Ecu_Config.h"),
        ),
        (
            "include/Ecu_DcmCallbackTypes.h",
            include_bytes!("../../../runtime/include/Ecu_DcmCallbackTypes.h"),
        ),
        (
            "include/Ecu_Status.h",
            include_bytes!("../../../runtime/include/Ecu_Status.h"),
        ),
        (
            "include/LSduR.h",
            include_bytes!("../../../runtime/include/LSduR.h"),
        ),
        (
            "include/NvM.h",
            include_bytes!("../../../runtime/include/NvM.h"),
        ),
        (
            "include/PduR.h",
            include_bytes!("../../../runtime/include/PduR.h"),
        ),
        (
            "include/SchM_Can.h",
            include_bytes!("../../../runtime/include/SchM_Can.h"),
        ),
        (
            "include/Security.h",
            include_bytes!("../../../runtime/include/Security.h"),
        ),
        (
            "include/Std_Types.h",
            include_bytes!("../../../runtime/include/Std_Types.h"),
        ),
        ("src/Can.c", include_bytes!("../../../runtime/src/Can.c")),
        (
            "src/CanIf.c",
            include_bytes!("../../../runtime/src/CanIf.c"),
        ),
        (
            "src/CanTp.c",
            include_bytes!("../../../runtime/src/CanTp.c"),
        ),
        ("src/Com.c", include_bytes!("../../../runtime/src/Com.c")),
        ("src/Dcm.c", include_bytes!("../../../runtime/src/Dcm.c")),
        ("src/Dem.c", include_bytes!("../../../runtime/src/Dem.c")),
        (
            "src/Ecu_Status.c",
            include_bytes!("../../../runtime/src/Ecu_Status.c"),
        ),
        (
            "src/LSduR.c",
            include_bytes!("../../../runtime/src/LSduR.c"),
        ),
        ("src/NvM.c", include_bytes!("../../../runtime/src/NvM.c")),
        (
            "src/NvM_HostStorage.c",
            include_bytes!("../../../runtime/src/NvM_HostStorage.c"),
        ),
        ("src/PduR.c", include_bytes!("../../../runtime/src/PduR.c")),
        (
            "src/Security.c",
            include_bytes!("../../../runtime/src/Security.c"),
        ),
    ];
    sources
        .iter()
        .map(|(name, bytes)| ((*name).into(), bytes.to_vec()))
        .collect()
}
