//! Product-authored structural coverage for the CAN and standard ECU inputs.
//! Tokens form ordered child groups; `?`, `*`, `+` mean 0..1, 0..n, 1..n.
//! `|` is an unordered choice within one group, not a separate sequence slot.
//! This is deliberately not an embedded or converted AUTOSAR schema.

pub const RELEASE: &str = "R24-11";
pub const RULES_VERSION: &str = "1.0.0";
pub const STRUCTURES: &[(&str, &str)] = &[
    ("AUTOSAR", "ADMIN-DATA? AR-PACKAGES?"),
    ("AR-PACKAGES", "AR-PACKAGE+"),
    (
        "AR-PACKAGE",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? ELEMENTS? AR-PACKAGES?",
    ),
    (
        "ELEMENTS",
        "ECUC-MODULE-CONFIGURATION-VALUES|I-SIGNAL|I-SIGNAL-I-PDU|N-PDU|DCM-I-PDU|CAN-FRAME|CAN-CLUSTER|ECU-INSTANCE|SYSTEM|SYSTEM-SIGNAL|SW-BASE-TYPE|IMPLEMENTATION-DATA-TYPE|APPLICATION-PRIMITIVE-DATA-TYPE|DATA-TYPE-MAPPING-SET|SENDER-RECEIVER-INTERFACE|CLIENT-SERVER-INTERFACE|APPLICATION-SW-COMPONENT-TYPE|SERVICE-SW-COMPONENT-TYPE|COMPOSITION-SW-COMPONENT-TYPE|BSW-MODULE-ENTRY|BSW-MODULE-DESCRIPTION|BSW-IMPLEMENTATION*",
    ),
    ("ADMIN-DATA", "SDGS?"),
    ("SDGS", "SDG+"),
    ("SDG", "SDG|SD*"),
    (
        "ECUC-MODULE-CONFIGURATION-VALUES",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? DEFINITION-REF? ECUC-DEF-EDITION? IMPLEMENTATION-CONFIG-VARIANT? MODULE-DESCRIPTION-REF? POST-BUILD-VARIANT-USED? CONTAINERS?",
    ),
    ("CONTAINERS", "ECUC-CONTAINER-VALUE+"),
    ("SUB-CONTAINERS", "ECUC-CONTAINER-VALUE+"),
    (
        "ECUC-CONTAINER-VALUE",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? INDEX? DEFINITION-REF? PARAMETER-VALUES? REFERENCE-VALUES? SUB-CONTAINERS?",
    ),
    (
        "PARAMETER-VALUES",
        "ECUC-NUMERICAL-PARAM-VALUE|ECUC-TEXTUAL-PARAM-VALUE+",
    ),
    ("REFERENCE-VALUES", "ECUC-REFERENCE-VALUE+"),
    (
        "ECUC-NUMERICAL-PARAM-VALUE",
        "INDEX? DEFINITION-REF? VALUE?",
    ),
    ("ECUC-TEXTUAL-PARAM-VALUE", "INDEX? DEFINITION-REF? VALUE?"),
    ("ECUC-REFERENCE-VALUE", "INDEX? DEFINITION-REF? VALUE-REF?"),
    (
        "I-SIGNAL",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? DATA-TYPE-POLICY? INIT-VALUE? LENGTH? NETWORK-REPRESENTATION-PROPS? SYSTEM-SIGNAL-REF?",
    ),
    (
        "I-SIGNAL-I-PDU",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? LENGTH? I-SIGNAL-TO-PDU-MAPPINGS?",
    ),
    (
        "N-PDU",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? LENGTH?",
    ),
    (
        "DCM-I-PDU",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? LENGTH?",
    ),
    ("I-SIGNAL-TO-PDU-MAPPINGS", "I-SIGNAL-TO-I-PDU-MAPPING+"),
    (
        "I-SIGNAL-TO-I-PDU-MAPPING",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? I-SIGNAL-REF? PACKING-BYTE-ORDER? START-POSITION? TRANSFER-PROPERTY?",
    ),
    (
        "CAN-FRAME",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? FRAME-LENGTH? PDU-TO-FRAME-MAPPINGS?",
    ),
    ("PDU-TO-FRAME-MAPPINGS", "PDU-TO-FRAME-MAPPING+"),
    (
        "PDU-TO-FRAME-MAPPING",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? PACKING-BYTE-ORDER? PDU-REF? START-POSITION?",
    ),
    (
        "CAN-CLUSTER",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? CAN-CLUSTER-VARIANTS?",
    ),
    ("CAN-CLUSTER-VARIANTS", "CAN-CLUSTER-CONDITIONAL+"),
    ("CAN-CLUSTER-CONDITIONAL", "BAUDRATE? PHYSICAL-CHANNELS?"),
    ("PHYSICAL-CHANNELS", "CAN-PHYSICAL-CHANNEL+"),
    (
        "CAN-PHYSICAL-CHANNEL",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? COMM-CONNECTORS? FRAME-TRIGGERINGS? I-SIGNAL-TRIGGERINGS? PDU-TRIGGERINGS?",
    ),
    (
        "COMM-CONNECTORS",
        "COMMUNICATION-CONNECTOR-REF-CONDITIONAL+",
    ),
    (
        "COMMUNICATION-CONNECTOR-REF-CONDITIONAL",
        "COMMUNICATION-CONNECTOR-REF",
    ),
    ("FRAME-TRIGGERINGS", "CAN-FRAME-TRIGGERING+"),
    (
        "CAN-FRAME-TRIGGERING",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? FRAME-PORT-REFS? FRAME-REF? PDU-TRIGGERINGS? CAN-ADDRESSING-MODE? CAN-FD-FRAME-SUPPORT? IDENTIFIER?",
    ),
    ("FRAME-PORT-REFS", "FRAME-PORT-REF+"),
    (
        "PDU-TRIGGERINGS",
        "PDU-TRIGGERING|PDU-TRIGGERING-REF-CONDITIONAL+",
    ),
    ("PDU-TRIGGERING-REF-CONDITIONAL", "PDU-TRIGGERING-REF"),
    (
        "PDU-TRIGGERING",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? I-PDU-PORT-REFS? I-PDU-REF? I-SIGNAL-TRIGGERINGS?",
    ),
    ("I-PDU-PORT-REFS", "I-PDU-PORT-REF+"),
    (
        "I-SIGNAL-TRIGGERINGS",
        "I-SIGNAL-TRIGGERING|I-SIGNAL-TRIGGERING-REF-CONDITIONAL+",
    ),
    (
        "I-SIGNAL-TRIGGERING-REF-CONDITIONAL",
        "I-SIGNAL-TRIGGERING-REF",
    ),
    (
        "I-SIGNAL-TRIGGERING",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? I-SIGNAL-PORT-REFS? I-SIGNAL-REF?",
    ),
    ("I-SIGNAL-PORT-REFS", "I-SIGNAL-PORT-REF+"),
    (
        "ECU-INSTANCE",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? COMM-CONTROLLERS? CONNECTORS?",
    ),
    ("COMM-CONTROLLERS", "CAN-COMMUNICATION-CONTROLLER+"),
    (
        "CAN-COMMUNICATION-CONTROLLER",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA?",
    ),
    (
        "CONNECTORS",
        "CAN-COMMUNICATION-CONNECTOR|ASSEMBLY-SW-CONNECTOR+",
    ),
    (
        "CAN-COMMUNICATION-CONNECTOR",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? COMM-CONTROLLER-REF? ECU-COMM-PORT-INSTANCES?",
    ),
    (
        "ECU-COMM-PORT-INSTANCES",
        "FRAME-PORT|I-PDU-PORT|I-SIGNAL-PORT+",
    ),
    (
        "FRAME-PORT",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? COMMUNICATION-DIRECTION?",
    ),
    (
        "I-PDU-PORT",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? COMMUNICATION-DIRECTION?",
    ),
    (
        "I-SIGNAL-PORT",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? COMMUNICATION-DIRECTION? FIRST-TIMEOUT? TIMEOUT?",
    ),
    (
        "SYSTEM",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? ECU-EXTRACT-VERSION? FIBEX-ELEMENTS? MAPPINGS? ROOT-SOFTWARE-COMPOSITIONS?",
    ),
    ("FIBEX-ELEMENTS", "FIBEX-ELEMENT-REF-CONDITIONAL+"),
    ("FIBEX-ELEMENT-REF-CONDITIONAL", "FIBEX-ELEMENT-REF"),
    ("MAPPINGS", "SYSTEM-MAPPING+"),
    (
        "SYSTEM-MAPPING",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? DATA-MAPPINGS? SW-MAPPINGS?",
    ),
    ("DATA-MAPPINGS", "SENDER-RECEIVER-TO-SIGNAL-MAPPING+"),
    (
        "SENDER-RECEIVER-TO-SIGNAL-MAPPING",
        "COMMUNICATION-DIRECTION? DATA-ELEMENT-IREF SYSTEM-SIGNAL-REF",
    ),
    (
        "DATA-ELEMENT-IREF",
        "CONTEXT-COMPONENT-REF* CONTEXT-COMPOSITION-REF? CONTEXT-PORT-REF? TARGET-DATA-PROTOTYPE-REF",
    ),
    ("SW-MAPPINGS", "SWC-TO-ECU-MAPPING+"),
    (
        "SWC-TO-ECU-MAPPING",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? COMPONENT-IREFS? ECU-INSTANCE-REF?",
    ),
    ("COMPONENT-IREFS", "COMPONENT-IREF+"),
    (
        "COMPONENT-IREF",
        "CONTEXT-COMPOSITION-REF? TARGET-COMPONENT-REF",
    ),
    (
        "ROOT-SOFTWARE-COMPOSITIONS",
        "ROOT-SW-COMPOSITION-PROTOTYPE+",
    ),
    (
        "ROOT-SW-COMPOSITION-PROTOTYPE",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? SOFTWARE-COMPOSITION-TREF",
    ),
    (
        "SYSTEM-SIGNAL",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA?",
    ),
    (
        "SW-BASE-TYPE",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? BASE-TYPE-SIZE? BASE-TYPE-ENCODING? NATIVE-DECLARATION?",
    ),
    (
        "IMPLEMENTATION-DATA-TYPE",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? SW-DATA-DEF-PROPS? SUB-ELEMENTS?",
    ),
    ("SUB-ELEMENTS", "IMPLEMENTATION-DATA-TYPE-ELEMENT+"),
    (
        "IMPLEMENTATION-DATA-TYPE-ELEMENT",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? ARRAY-SIZE? ARRAY-SIZE-SEMANTICS? SW-DATA-DEF-PROPS?",
    ),
    (
        "APPLICATION-PRIMITIVE-DATA-TYPE",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? SW-DATA-DEF-PROPS?",
    ),
    ("SW-DATA-DEF-PROPS", "SW-DATA-DEF-PROPS-VARIANTS?"),
    (
        "NETWORK-REPRESENTATION-PROPS",
        "SW-DATA-DEF-PROPS-VARIANTS?",
    ),
    (
        "SW-DATA-DEF-PROPS-VARIANTS",
        "SW-DATA-DEF-PROPS-CONDITIONAL+",
    ),
    (
        "SW-DATA-DEF-PROPS-CONDITIONAL",
        "BASE-TYPE-REF? IMPLEMENTATION-DATA-TYPE-REF?",
    ),
    (
        "DATA-TYPE-MAPPING-SET",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? DATA-TYPE-MAPS?",
    ),
    ("DATA-TYPE-MAPS", "DATA-TYPE-MAP+"),
    (
        "DATA-TYPE-MAP",
        "APPLICATION-DATA-TYPE-REF IMPLEMENTATION-DATA-TYPE-REF",
    ),
    (
        "SENDER-RECEIVER-INTERFACE",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? IS-SERVICE? DATA-ELEMENTS?",
    ),
    ("DATA-ELEMENTS", "VARIABLE-DATA-PROTOTYPE+"),
    (
        "VARIABLE-DATA-PROTOTYPE",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? TYPE-TREF?",
    ),
    (
        "CLIENT-SERVER-INTERFACE",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? IS-SERVICE? SERVICE-KIND? OPERATIONS?",
    ),
    ("OPERATIONS", "CLIENT-SERVER-OPERATION+"),
    (
        "CLIENT-SERVER-OPERATION",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? ARGUMENTS?",
    ),
    ("ARGUMENTS", "ARGUMENT-DATA-PROTOTYPE|SW-SERVICE-ARG+"),
    (
        "ARGUMENT-DATA-PROTOTYPE",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? TYPE-TREF? DIRECTION? SERVER-ARGUMENT-IMPL-POLICY?",
    ),
    (
        "SW-SERVICE-ARG",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? DIRECTION? SW-DATA-DEF-PROPS?",
    ),
    (
        "RETURN-TYPE",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? DIRECTION? SW-DATA-DEF-PROPS?",
    ),
    (
        "APPLICATION-SW-COMPONENT-TYPE",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? PORTS? INTERNAL-BEHAVIORS?",
    ),
    (
        "SERVICE-SW-COMPONENT-TYPE",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? PORTS? INTERNAL-BEHAVIORS?",
    ),
    (
        "COMPOSITION-SW-COMPONENT-TYPE",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? PORTS? COMPONENTS? CONNECTORS?",
    ),
    ("COMPONENTS", "SW-COMPONENT-PROTOTYPE+"),
    (
        "SW-COMPONENT-PROTOTYPE",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? TYPE-TREF",
    ),
    (
        "ASSEMBLY-SW-CONNECTOR",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? PROVIDER-IREF REQUESTER-IREF",
    ),
    ("PROVIDER-IREF", "CONTEXT-COMPONENT-REF? TARGET-P-PORT-REF"),
    ("REQUESTER-IREF", "CONTEXT-COMPONENT-REF? TARGET-R-PORT-REF"),
    ("PORTS", "P-PORT-PROTOTYPE|R-PORT-PROTOTYPE+"),
    (
        "P-PORT-PROTOTYPE",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? PROVIDED-COM-SPECS? PROVIDED-INTERFACE-TREF?",
    ),
    (
        "R-PORT-PROTOTYPE",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? REQUIRED-COM-SPECS? REQUIRED-INTERFACE-TREF?",
    ),
    (
        "PROVIDED-COM-SPECS",
        "NONQUEUED-SENDER-COM-SPEC|SERVER-COM-SPEC+",
    ),
    (
        "REQUIRED-COM-SPECS",
        "NONQUEUED-RECEIVER-COM-SPEC|CLIENT-COM-SPEC+",
    ),
    ("NONQUEUED-SENDER-COM-SPEC", "DATA-ELEMENT-REF? INIT-VALUE?"),
    (
        "NONQUEUED-RECEIVER-COM-SPEC",
        "DATA-ELEMENT-REF? ALIVE-TIMEOUT? HANDLE-NEVER-RECEIVED? HANDLE-TIMEOUT-TYPE? INIT-VALUE?",
    ),
    ("SERVER-COM-SPEC", "OPERATION-REF? QUEUE-LENGTH?"),
    ("CLIENT-COM-SPEC", "OPERATION-REF?"),
    ("INIT-VALUE", "NUMERICAL-VALUE-SPECIFICATION"),
    ("NUMERICAL-VALUE-SPECIFICATION", "SHORT-LABEL? VALUE"),
    (
        "INTERNAL-BEHAVIORS",
        "SWC-INTERNAL-BEHAVIOR|BSW-INTERNAL-BEHAVIOR+",
    ),
    (
        "SWC-INTERNAL-BEHAVIOR",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? DATA-TYPE-MAPPING-REFS? EVENTS? RUNNABLES? SUPPORTS-MULTIPLE-INSTANTIATION?",
    ),
    ("DATA-TYPE-MAPPING-REFS", "DATA-TYPE-MAPPING-REF+"),
    (
        "EVENTS",
        "TIMING-EVENT|OPERATION-INVOKED-EVENT|BSW-TIMING-EVENT+",
    ),
    (
        "TIMING-EVENT",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? START-ON-EVENT-REF? OFFSET? PERIOD?",
    ),
    (
        "OPERATION-INVOKED-EVENT",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? START-ON-EVENT-REF? OPERATION-IREF?",
    ),
    ("RUNNABLES", "RUNNABLE-ENTITY+"),
    (
        "RUNNABLE-ENTITY",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? MINIMUM-START-INTERVAL? CAN-BE-INVOKED-CONCURRENTLY? DATA-RECEIVE-POINT-BY-ARGUMENTS? DATA-SEND-POINTS? SERVER-CALL-POINTS? SYMBOL?",
    ),
    ("DATA-RECEIVE-POINT-BY-ARGUMENTS", "VARIABLE-ACCESS+"),
    ("DATA-SEND-POINTS", "VARIABLE-ACCESS+"),
    (
        "VARIABLE-ACCESS",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? ACCESSED-VARIABLE?",
    ),
    ("ACCESSED-VARIABLE", "AUTOSAR-VARIABLE-IREF"),
    (
        "AUTOSAR-VARIABLE-IREF",
        "PORT-PROTOTYPE-REF? TARGET-DATA-PROTOTYPE-REF",
    ),
    ("SERVER-CALL-POINTS", "SYNCHRONOUS-SERVER-CALL-POINT+"),
    (
        "SYNCHRONOUS-SERVER-CALL-POINT",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? OPERATION-IREF?",
    ),
    (
        "OPERATION-IREF",
        "CONTEXT-P-PORT-REF|CONTEXT-R-PORT-REF? TARGET-PROVIDED-OPERATION-REF|TARGET-REQUIRED-OPERATION-REF",
    ),
    (
        "BSW-MODULE-ENTRY",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? IS-REENTRANT? IS-SYNCHRONOUS? CALL-TYPE? EXECUTION-CONTEXT? RETURN-TYPE? ARGUMENTS?",
    ),
    (
        "BSW-MODULE-DESCRIPTION",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? IMPLEMENTED-ENTRYS? INTERNAL-BEHAVIORS?",
    ),
    ("IMPLEMENTED-ENTRYS", "BSW-MODULE-ENTRY-REF-CONDITIONAL+"),
    ("BSW-MODULE-ENTRY-REF-CONDITIONAL", "BSW-MODULE-ENTRY-REF"),
    (
        "BSW-IMPLEMENTATION",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? PROGRAMMING-LANGUAGE? SW-VERSION? AR-RELEASE-VERSION? BEHAVIOR-REF?",
    ),
    (
        "BSW-INTERNAL-BEHAVIOR",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? ENTITYS? EVENTS?",
    ),
    ("ENTITYS", "BSW-SCHEDULABLE-ENTITY+"),
    (
        "BSW-SCHEDULABLE-ENTITY",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? IMPLEMENTED-ENTRY-REF?",
    ),
    (
        "BSW-TIMING-EVENT",
        "SHORT-NAME LONG-NAME? DESC? CATEGORY? ADMIN-DATA? STARTS-ON-EVENT-REF? PERIOD?",
    ),
];

// These wrappers contain an XML choice wider than the authored product subset.
// An unlisted alternative contributes to wrapper cardinality, but remains
// unsupported; it never obtains the rules of one of the supported alternatives.
pub const OPEN_CHOICES: &[&str] = &[
    "ELEMENTS",
    "PARAMETER-VALUES",
    "REFERENCE-VALUES",
    "INIT-VALUE",
    "PHYSICAL-CHANNELS",
    "COMM-CONTROLLERS",
    "CONNECTORS",
    "PORTS",
    "DATA-MAPPINGS",
    "SW-MAPPINGS",
    "ARGUMENTS",
    "PROVIDED-COM-SPECS",
    "REQUIRED-COM-SPECS",
    "INTERNAL-BEHAVIORS",
    "EVENTS",
    "SERVER-CALL-POINTS",
    "SUB-ELEMENTS",
    "DATA-ELEMENTS",
];

// XML lexical types, separate from ECUC definition constraints/ranges.
pub const SCALARS: &[(&str, &str)] = &[
    ("SHORT-NAME", "identifier"),
    ("SYMBOL", "symbol"),
    ("SHORT-LABEL", "identifier"),
    ("CATEGORY", "text"),
    ("SD", "text"),
    ("NATIVE-DECLARATION", "text"),
    ("ECUC-DEF-EDITION", "revision"),
    ("ECU-EXTRACT-VERSION", "revision"),
    ("SW-VERSION", "revision"),
    ("AR-RELEASE-VERSION", "revision"),
    ("LENGTH", "integer"),
    ("FRAME-LENGTH", "integer"),
    ("START-POSITION", "integer"),
    ("IDENTIFIER", "integer"),
    ("BAUDRATE", "unsigned"),
    ("BASE-TYPE-SIZE", "unsigned"),
    ("ARRAY-SIZE", "unsigned"),
    ("QUEUE-LENGTH", "unsigned"),
    ("INDEX", "unsigned"),
    ("PERIOD", "number"),
    ("OFFSET", "number"),
    ("FIRST-TIMEOUT", "number"),
    ("TIMEOUT", "number"),
    ("ALIVE-TIMEOUT", "number"),
    ("MINIMUM-START-INTERVAL", "number"),
    ("CAN-FD-FRAME-SUPPORT", "boolean"),
    ("CAN-BE-INVOKED-CONCURRENTLY", "boolean"),
    ("IS-REENTRANT", "boolean"),
    ("IS-SYNCHRONOUS", "boolean"),
    ("IS-SERVICE", "boolean"),
    ("HANDLE-NEVER-RECEIVED", "boolean"),
    ("SUPPORTS-MULTIPLE-INSTANTIATION", "boolean"),
    ("POST-BUILD-VARIANT-USED", "boolean"),
    (
        "PACKING-BYTE-ORDER",
        "enum:MOST-SIGNIFICANT-BYTE-FIRST|MOST-SIGNIFICANT-BYTE-LAST|OPAQUE",
    ),
    ("COMMUNICATION-DIRECTION", "enum:IN|OUT"),
    ("DIRECTION", "enum:IN|INOUT|OUT"),
    ("CAN-ADDRESSING-MODE", "enum:STANDARD|EXTENDED"),
    (
        "DATA-TYPE-POLICY",
        "enum:DDS-SERVICE|DDS-SIGNAL|LEGACY|NETWORK-REPRESENTATION-FROM-COM-SPEC|OVERRIDE|PORT-INTERFACE-DEFINITION|TRANSFORMING-I-SIGNAL",
    ),
    (
        "IMPLEMENTATION-CONFIG-VARIANT",
        "enum:PRECONFIGURED-CONFIGURATION|RECOMMENDED-CONFIGURATION|VARIANT-PRE-COMPILE|VARIANT-LINK-TIME|VARIANT-POST-BUILD|VARIANT-POST-BUILD-LOADABLE|VARIANT-POST-BUILD-SELECTABLE",
    ),
    (
        "TRANSFER-PROPERTY",
        "enum:PENDING|TRIGGERED|TRIGGERED-ON-CHANGE|TRIGGERED-ON-CHANGE-WITHOUT-REPETITION|TRIGGERED-WITHOUT-REPETITION",
    ),
    ("ARRAY-SIZE-SEMANTICS", "enum:FIXED-SIZE|VARIABLE-SIZE"),
    (
        "SERVER-ARGUMENT-IMPL-POLICY",
        "enum:USE-ARGUMENT-TYPE|USE-ARRAY-BASE-TYPE|USE-VOID",
    ),
    ("HANDLE-TIMEOUT-TYPE", "enum:NONE|REPLACE|SUBSTITUTE"),
    (
        "CALL-TYPE",
        "enum:CALLBACK|CALLOUT|INTERRUPT|REGULAR|SCHEDULED",
    ),
    (
        "EXECUTION-CONTEXT",
        "enum:HOOK|INTERRUPT-CAT-1|INTERRUPT-CAT-2|TASK|UNSPECIFIED",
    ),
    ("PROGRAMMING-LANGUAGE", "enum:C|CPP|JAVA"),
    ("BASE-TYPE-ENCODING", "text"),
    (
        "SERVICE-KIND",
        "enum:ANY-STANDARDIZED|BASIC-SOFTWARE-MODE-MANAGER|COM-MANAGER|CRYPTO-KEY-MANAGEMENT|CRYPTO-SERVICE-MANAGER|DEFAULT-ERROR-TRACER|DEVELOPMENT-ERROR-TRACER|DIAGNOSTIC-COMMUNICATION-MANAGER|DIAGNOSTIC-EVENT-MANAGER|DIAGNOSTIC-LOG-AND-TRACE|ECU-MANAGER|ERROR-TRACER|FUNCTION-INHIBITION-MANAGER|HARDWARE-TEST-MANAGER|INTRUSION-DETECTION-SECURITY-MANAGEMENT|J-1939-DCM|J-1939-REQUEST-MANAGER|NON-VOLATILE-RAM-MANAGER|OPERATING-SYSTEM|SECURE-ON-BOARD-COMMUNICATION|SYNC-BASE-TIME-MANAGER|V-2-X-FACILITIES|V-2-X-MANAGEMENT|VENDOR-SPECIFIC|WATCH-DOG-MANAGER",
    ),
    ("VALUE", "context"),
];

pub const REFERENCES: &[&str] = &[
    "DEFINITION-REF",
    "VALUE-REF",
    "MODULE-DESCRIPTION-REF",
    "I-SIGNAL-REF",
    "SYSTEM-SIGNAL-REF",
    "PDU-REF",
    "FRAME-REF",
    "FRAME-PORT-REF",
    "I-PDU-REF",
    "I-PDU-PORT-REF",
    "I-SIGNAL-PORT-REF",
    "I-SIGNAL-TRIGGERING-REF",
    "PDU-TRIGGERING-REF",
    "COMMUNICATION-CONNECTOR-REF",
    "COMM-CONTROLLER-REF",
    "FIBEX-ELEMENT-REF",
    "CONTEXT-COMPONENT-REF",
    "CONTEXT-COMPOSITION-REF",
    "CONTEXT-PORT-REF",
    "TARGET-DATA-PROTOTYPE-REF",
    "TARGET-COMPONENT-REF",
    "ECU-INSTANCE-REF",
    "SOFTWARE-COMPOSITION-TREF",
    "BASE-TYPE-REF",
    "APPLICATION-DATA-TYPE-REF",
    "IMPLEMENTATION-DATA-TYPE-REF",
    "TYPE-TREF",
    "TARGET-P-PORT-REF",
    "TARGET-R-PORT-REF",
    "PROVIDED-INTERFACE-TREF",
    "REQUIRED-INTERFACE-TREF",
    "DATA-ELEMENT-REF",
    "OPERATION-REF",
    "DATA-TYPE-MAPPING-REF",
    "START-ON-EVENT-REF",
    "PORT-PROTOTYPE-REF",
    "CONTEXT-P-PORT-REF",
    "CONTEXT-R-PORT-REF",
    "TARGET-PROVIDED-OPERATION-REF",
    "TARGET-REQUIRED-OPERATION-REF",
    "BSW-MODULE-ENTRY-REF",
    "BEHAVIOR-REF",
    "IMPLEMENTED-ENTRY-REF",
    "STARTS-ON-EVENT-REF",
];

pub fn coverage_rows() -> Vec<(&'static str, String, &'static str)> {
    let mut rows = Vec::new();
    for (name, _) in STRUCTURES {
        rows.push(("schema", format!("native.structure.{name}"), *name));
    }
    for (name, _) in SCALARS {
        rows.push(("schema", format!("native.type.{name}"), *name));
    }
    for name in REFERENCES {
        rows.push(("schema", format!("native.type.{name}"), *name));
    }
    rows.push(("source-safety", "native.source-safety".into(), "AUTOSAR"));
    rows.sort_by(|left, right| left.1.cmp(&right.1));
    rows
}
