"""
AUTOSAR Composition Builder — generates multi-tab AUTOSAR R22-11 Composition SWC workbook from JSON.

Usage:
    python generate_composition.py <input.json> <output.xlsx>

Input JSON schema:
{
  "item": {name, abbr, project, doc_id, revision, date, author, approver, company},
  "composition": {name, description, implementation_type},
  "swc_instances": [
    {id, name, swc_type, role, multiplicity}
  ],
  "assembly_connectors": [
    {id, source_swc, source_port, target_swc, target_port, interface_name}
  ],
  "delegation_connectors": [
    {id, swc_instance, swc_port, boundary_port, direction}  // direction: Provided|Required
  ],
  "boundary_ports": [
    {id, name, category, direction, interface_name}
  ],
  "port_compatibility_rules": [
    {rule_id, description, checks}
  ]
}
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from datetime import date as today_date

from openpyxl import Workbook
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter


# Styling
FONT_NAME = "Calibri"
NAVY = "1F3864"
LIGHT_BLUE = "D9E2F3"
ALT_ROW = "F2F2F2"
WARN_YELLOW = "FFF2CC"
GREEN_OK = "C6EFCE"
RED_BAD = "F8CBAD"
THIN = Side(border_style="thin", color="BFBFBF")
BORDER_ALL = Border(left=THIN, right=THIN, top=THIN, bottom=THIN)


def title_font(size: int = 16) -> Font:
    return Font(name=FONT_NAME, size=size, bold=True, color="FFFFFF")


def header_font() -> Font:
    return Font(name=FONT_NAME, size=11, bold=True, color="FFFFFF")


def body_font() -> Font:
    return Font(name=FONT_NAME, size=10)


def style_title_row(ws, row: int, last_col: int, text: str) -> None:
    ws.merge_cells(start_row=row, start_column=1, end_row=row, end_column=last_col)
    cell = ws.cell(row=row, column=1, value=text)
    cell.font = title_font(14)
    cell.fill = PatternFill("solid", fgColor=NAVY)
    cell.alignment = Alignment(horizontal="center", vertical="center")
    ws.row_dimensions[row].height = 28


def style_header_row(ws, row: int, headers: list[str]) -> None:
    for col, h in enumerate(headers, start=1):
        cell = ws.cell(row=row, column=col, value=h)
        cell.font = header_font()
        cell.fill = PatternFill("solid", fgColor=NAVY)
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)
        cell.border = BORDER_ALL
    ws.row_dimensions[row].height = 32


def stripe_body(ws, start_row: int, end_row: int, last_col: int) -> None:
    for r in range(start_row, end_row + 1):
        fill = PatternFill("solid", fgColor=ALT_ROW) if (r - start_row) % 2 else None
        for c in range(1, last_col + 1):
            cell = ws.cell(row=r, column=c)
            cell.font = body_font()
            cell.alignment = Alignment(vertical="top", wrap_text=True)
            cell.border = BORDER_ALL
            if fill:
                cell.fill = fill


def autosize(ws, widths: dict[int, int]) -> None:
    for col, width in widths.items():
        ws.column_dimensions[get_column_letter(col)].width = width


# Tab builders

def build_title_page(wb: Workbook, item: dict, composition: dict) -> None:
    ws = wb.create_sheet("00_Title_Page")
    ws.sheet_view.showGridLines = False

    style_title_row(ws, 2, 4, "AUTOSAR R22-11 Composition SWC Specification")
    style_title_row(ws, 3, 4, f"{composition.get('name', '')} ({item.get('abbr', '')})")

    fields = [
        ("Project", item.get("project", "")),
        ("Composition Name", composition.get("name", "")),
        ("Document ID", item.get("doc_id", "")),
        ("Revision", item.get("revision", "")),
        ("Date", item.get("date", str(today_date.today()))),
        ("Author", item.get("author", "")),
        ("Approver", item.get("approver", "")),
        ("Company", item.get("company", "")),
        ("AUTOSAR Version", "R22-11 (Classic Platform)"),
    ]

    row = 6
    for label, value in fields:
        ws.cell(row=row, column=2, value=label).font = Font(name=FONT_NAME, size=11, bold=True, color=NAVY)
        ws.cell(row=row, column=3, value=value).font = body_font()
        ws.cell(row=row, column=3).alignment = Alignment(horizontal="left")
        row += 1

    autosize(ws, {1: 4, 2: 22, 3: 60, 4: 4})


def build_doc_control(wb: Workbook) -> None:
    ws = wb.create_sheet("01_Document_Control")
    ws.sheet_view.showGridLines = False

    style_title_row(ws, 1, 5, "Document Control")

    style_header_row(ws, 3, ["Revision", "Date", "Author", "Description of change", "Approver"])
    placeholders = [
        ("0.1", "", "", "Initial draft generated by autosar-composition-builder", ""),
        ("0.2", "", "", "Internal review comments incorporated", ""),
        ("1.0", "", "", "Released for architecture review", ""),
    ]
    for i, row_data in enumerate(placeholders, start=4):
        for col, val in enumerate(row_data, start=1):
            ws.cell(row=i, column=col, value=val)
    stripe_body(ws, 4, 4 + len(placeholders) - 1, 5)

    style_title_row(ws, 10, 5, "Distribution List")
    style_header_row(ws, 11, ["Name", "Role", "Organization", "Email", "Notes"])
    for i in range(12, 16):
        for c in range(1, 6):
            ws.cell(row=i, column=c, value="")
    stripe_body(ws, 12, 15, 5)

    autosize(ws, {1: 12, 2: 14, 3: 22, 4: 50, 5: 22})


def build_composition_identity(wb: Workbook, item: dict, composition: dict) -> None:
    ws = wb.create_sheet("02_Composition_Identity")
    ws.sheet_view.showGridLines = False
    style_title_row(ws, 1, 4, "Composition Identity")

    fields = [
        ("Composition Name", composition.get("name", "")),
        ("Abbreviation", item.get("abbr", "")),
        ("Description", composition.get("description", "")),
        ("Implementation Type", composition.get("implementation_type", "Software")),
        ("Vendor/Owner", item.get("company", "")),
    ]

    row = 3
    for label, value in fields:
        ws.cell(row=row, column=1, value=label).font = Font(name=FONT_NAME, bold=True, size=10)
        ws.cell(row=row, column=2, value=value).font = body_font()
        ws.cell(row=row, column=2).alignment = Alignment(wrap_text=True, vertical="top")
        row += 1

    autosize(ws, {1: 22, 2: 60})


def build_swc_instances(wb: Workbook, instances: list[dict]) -> None:
    ws = wb.create_sheet("03_SWC_Instances")
    ws.sheet_view.showGridLines = False
    style_title_row(ws, 1, 5, "Contained SWC Instances")

    style_header_row(ws, 3, ["Instance ID", "Instance Name", "SWC Type", "Role", "Multiplicity"])
    if not instances:
        instances = []
    for i, inst in enumerate(instances, start=4):
        ws.cell(row=i, column=1, value=inst.get("id", ""))
        ws.cell(row=i, column=2, value=inst.get("name", ""))
        ws.cell(row=i, column=3, value=inst.get("swc_type", ""))
        ws.cell(row=i, column=4, value=inst.get("role", ""))
        ws.cell(row=i, column=5, value=inst.get("multiplicity", "1"))
    if instances:
        stripe_body(ws, 4, 3 + len(instances), 5)

    autosize(ws, {1: 14, 2: 24, 3: 24, 4: 16, 5: 14})


def build_assembly_connectors(wb: Workbook, connectors: list[dict]) -> None:
    ws = wb.create_sheet("04_Assembly_Connectors")
    ws.sheet_view.showGridLines = False
    style_title_row(ws, 1, 6, "Assembly Connectors (SWC-to-SWC Port Mappings)")

    style_header_row(ws, 3, ["Connector ID", "Source SWC", "Source Port", "Target SWC", "Target Port", "Interface"])
    if not connectors:
        connectors = []
    for i, conn in enumerate(connectors, start=4):
        ws.cell(row=i, column=1, value=conn.get("id", ""))
        ws.cell(row=i, column=2, value=conn.get("source_swc", ""))
        ws.cell(row=i, column=3, value=conn.get("source_port", ""))
        ws.cell(row=i, column=4, value=conn.get("target_swc", ""))
        ws.cell(row=i, column=5, value=conn.get("target_port", ""))
        ws.cell(row=i, column=6, value=conn.get("interface_name", ""))
    if connectors:
        stripe_body(ws, 4, 3 + len(connectors), 6)

    autosize(ws, {1: 14, 2: 18, 3: 18, 4: 18, 5: 18, 6: 24})


def build_delegation_connectors(wb: Workbook, delegates: list[dict]) -> None:
    ws = wb.create_sheet("05_Delegation_Connectors")
    ws.sheet_view.showGridLines = False
    style_title_row(ws, 1, 5, "Delegation Connectors (to Boundary)")

    style_header_row(ws, 3, ["Delegate ID", "SWC Instance", "SWC Port", "Boundary Port", "Direction"])
    if not delegates:
        delegates = []
    for i, dlg in enumerate(delegates, start=4):
        ws.cell(row=i, column=1, value=dlg.get("id", ""))
        ws.cell(row=i, column=2, value=dlg.get("swc_instance", ""))
        ws.cell(row=i, column=3, value=dlg.get("swc_port", ""))
        ws.cell(row=i, column=4, value=dlg.get("boundary_port", ""))
        ws.cell(row=i, column=5, value=dlg.get("direction", ""))
    if delegates:
        stripe_body(ws, 4, 3 + len(delegates), 5)

    autosize(ws, {1: 14, 2: 20, 3: 18, 4: 20, 5: 14})


def build_boundary_ports(wb: Workbook, ports: list[dict]) -> None:
    ws = wb.create_sheet("06_Boundary_Ports")
    ws.sheet_view.showGridLines = False
    style_title_row(ws, 1, 5, "Composition Boundary Port Aggregation")

    style_header_row(ws, 3, ["Port ID", "Port Name", "Category", "Direction", "Interface"])
    if not ports:
        ports = []
    for i, port in enumerate(ports, start=4):
        ws.cell(row=i, column=1, value=port.get("id", ""))
        ws.cell(row=i, column=2, value=port.get("name", ""))
        ws.cell(row=i, column=3, value=port.get("category", ""))
        ws.cell(row=i, column=4, value=port.get("direction", ""))
        ws.cell(row=i, column=5, value=port.get("interface_name", ""))
    if ports:
        stripe_body(ws, 4, 3 + len(ports), 5)

    autosize(ws, {1: 10, 2: 20, 3: 12, 4: 14, 5: 24})


def build_hierarchy_tree(wb: Workbook, instances: list[dict]) -> None:
    ws = wb.create_sheet("07_Hierarchy_Tree")
    ws.sheet_view.showGridLines = False
    style_title_row(ws, 1, 3, "Composition Hierarchy Tree")

    ws.cell(row=3, column=1, value="Composition").font = Font(name=FONT_NAME, bold=True, size=11)
    row = 4
    for inst in instances:
        ws.cell(row=row, column=2, value=f"  {inst.get('name', '')} ({inst.get('swc_type', '')})").font = body_font()
        row += 1

    autosize(ws, {1: 28, 2: 60})


def build_variation_points(wb: Workbook) -> None:
    ws = wb.create_sheet("08_Variation_Points")
    ws.sheet_view.showGridLines = False
    style_title_row(ws, 1, 4, "Variation Points (if applicable)")

    style_header_row(ws, 3, ["VP ID", "Description", "Variants", "Selection Criteria"])
    for i in range(4, 7):
        for c in range(1, 5):
            ws.cell(row=i, column=c, value="")

    autosize(ws, {1: 10, 2: 30, 3: 20, 4: 40})


def build_port_compatibility_rules(wb: Workbook) -> None:
    ws = wb.create_sheet("09_Port_Compatibility")
    ws.sheet_view.showGridLines = False
    style_title_row(ws, 1, 3, "Port Compatibility Rules")

    ws.cell(row=3, column=1, value="Rule").font = Font(name=FONT_NAME, bold=True, size=10)
    ws.cell(row=3, column=2, value="Description").font = Font(name=FONT_NAME, bold=True, size=10)
    rules = [
        ("R01", "Assembly connectors must link a Provided port to a Required port with compatible interface types."),
        ("R02", "Delegation connectors must map SWC port types to composition boundary port types."),
        ("R03", "Port multiplicity must be respected in assembly connector definitions."),
    ]
    for i, (rule_id, desc) in enumerate(rules, start=4):
        ws.cell(row=i, column=1, value=rule_id)
        ws.cell(row=i, column=2, value=desc)

    autosize(ws, {1: 8, 2: 80})


def build_validation_rules(wb: Workbook) -> None:
    ws = wb.create_sheet("10_Validation_Rules")
    ws.sheet_view.showGridLines = False
    style_title_row(ws, 1, 3, "Validation Rules and Constraints")

    ws.cell(row=3, column=1, value="Check").font = Font(name=FONT_NAME, bold=True, size=10)
    ws.cell(row=3, column=2, value="Description").font = Font(name=FONT_NAME, bold=True, size=10)
    checks = [
        ("V01", "No orphaned SWC instances (all instances must be part of at least one connector)."),
        ("V02", "All delegation connectors must reference valid SWC instances and ports."),
        ("V03", "Boundary ports must be referenced by delegation connectors."),
    ]
    for i, (check_id, desc) in enumerate(checks, start=4):
        ws.cell(row=i, column=1, value=check_id)
        ws.cell(row=i, column=2, value=desc)

    autosize(ws, {1: 8, 2: 80})


def build_references(wb: Workbook) -> None:
    ws = wb.create_sheet("11_References")
    ws.sheet_view.showGridLines = False
    style_title_row(ws, 1, 2, "References")

    style_header_row(ws, 3, ["Standard / Document", "Title"])
    refs = [
        ("AUTOSAR R22-11", "AUTOSAR Classic Platform Specification"),
        ("ISO 26262:2018", "Road vehicles - Functional safety"),
    ]
    for i, (ref, title) in enumerate(refs, start=4):
        ws.cell(row=i, column=1, value=ref)
        ws.cell(row=i, column=2, value=title)
    stripe_body(ws, 4, 3 + len(refs), 2)

    autosize(ws, {1: 24, 2: 60})


def generate(input_path: str, output_path: str) -> dict:
    with open(input_path, encoding="utf-8") as f:
        data = json.load(f)

    item = data.get("item", {})
    composition = data.get("composition", {})
    swc_instances = data.get("swc_instances", [])
    assembly_connectors = data.get("assembly_connectors", [])
    delegation_connectors = data.get("delegation_connectors", [])
    boundary_ports = data.get("boundary_ports", [])

    wb = Workbook()
    wb.remove(wb.active)

    build_title_page(wb, item, composition)
    build_doc_control(wb)
    build_composition_identity(wb, item, composition)
    build_swc_instances(wb, swc_instances)
    build_assembly_connectors(wb, assembly_connectors)
    build_delegation_connectors(wb, delegation_connectors)
    build_boundary_ports(wb, boundary_ports)
    build_hierarchy_tree(wb, swc_instances)
    build_variation_points(wb)
    build_port_compatibility_rules(wb)
    build_validation_rules(wb)
    build_references(wb)

    wb.active = 0
    _repository_notice(wb)
    wb.save(output_path)

    return {
        "composition_name": composition.get("name", "Unknown"),
        "swc_instances": len(swc_instances),
        "assembly_connectors": len(assembly_connectors),
        "delegation_connectors": len(delegation_connectors),
        "boundary_ports": len(boundary_ports),
        "output_path": output_path,
    }




def _repository_notice(wb):
    import json
    from pathlib import Path
    import sys
    for sheet in wb:
        for row in sheet:
            for cell in row:
                if cell.value == "APPROVED":
                    cell.value = "DOCUMENT CHECKS COMPLETE - review required"
                elif cell.value == "CONDITIONAL APPROVAL":
                    cell.value = "DOCUMENT ISSUES - review required"
                elif cell.value in ("Internal review comments incorporated", "Released for architecture review", "Initial release"):
                    cell.value = "TEMPLATE PLACEHOLDER - not a recorded project event"
    if "03_Coding_Rules_Catalog" in wb.sheetnames:
        rules = wb["03_Coding_Rules_Catalog"]
        col = rules.max_column + 1
        rules.cell(1, col, "Repository validation status")
        for row in range(2, rules.max_row + 1):
            rules.cell(row, col, "UNVERIFIED UPSTREAM TEMPLATE - rule ID/text/severity/CWE require authoritative review")
    ws = wb.create_sheet("Repository Scope")
    ws.append(["Field", "Value"])
    ws.append(["Purpose", "Document generation/review only; NOT a runtime test or certification"])
    ws.append(["Evidence", "Separate CONTENT / STRUCTURE / DRAFT; missing evidence remains unassessed"])
    ws.append(["Version", "Upstream AUTOSAR R22-11 templates; repository R24-11 obligations need verification"])
    ws.append(["Thresholds", "Upstream thresholds are advisory, not repository acceptance gates"])
    ws.append(["Templates", "Fixed example/default content requires review; not project facts"])
    if len(sys.argv) > 1 and Path(sys.argv[1]).suffix.lower() == ".json":
        with open(sys.argv[1], encoding="utf-8") as stream:
            provenance = json.load(stream).get("provenance", {})
        for key, value in provenance.items():
            ws.append([key, json.dumps(value, ensure_ascii=False) if isinstance(value, (dict, list)) else value])
    ws.column_dimensions["A"].width = 20
    ws.column_dimensions["B"].width = 100


if __name__ == "__main__":
    if len(sys.argv) != 3:
        print("Usage: python generate_composition.py <input.json> <output.xlsx>", file=sys.stderr)
        sys.exit(2)
    summary = generate(sys.argv[1], sys.argv[2])
    print(json.dumps(summary, indent=2))
